Algoritmo "MAIOR_NUMERO"
Var
   num1,num2,num3,maiorNumero:inteiro
Inicio
   escreva("Informe o 1° Número:")
   leia(num1)
   se num1>maiorNumero entao
      maiorNumero <- num1
   fimse
   escreva("Informe o 2° Númmero:")
   leia(num2)
   se num2>maiorNumero entao
      maiorNumero <- num2
   fimse
   escreva("Informe o 3° Número:")
   leia(num3)
   se num3>maiorNumero entao
      maiorNumero <- num3
   fimse
   escreva(maiorNumero)
Fimalgoritmo